In [1]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('hs7.csv',index_col='mean_depth')

df

,1,2,3,4,5,6,7
mean_depth,,,,,,,
0.01,0.004300,0.006735,0.008262,0.009708,0.011301,0.013350,0.017499
0.02,0.008600,0.013471,0.016524,0.019415,0.022602,0.026699,0.034997
0.03,0.012901,0.020206,0.024787,0.029123,0.033903,0.040049,0.052496
0.04,0.017201,0.026942,0.033049,0.038830,0.045203,0.053398,0.069995
0.05,0.021501,0.033677,0.041311,0.048538,0.056504,0.066748,0.087494
...,...,...,...,...,...,...,...
1.95,0.838536,1.313402,1.611129,1.892984,2.203669,2.603166,3.412254
1.96,0.842836,1.320138,1.619391,1.902691,2.214970,2.616516,3.429753
1.97,0.847136,1.326873,1.627654,1.912399,2.226271,2.629866,3.447252
1.98,0.851437,1.333608,1.635916,1.922106,2.237572,2.643215,3.464750
1.99,0.855737,1.340344,1.644178,1.931814,2.248873,2.656565,3.482249

In [34]:
df = pd.read_csv('hs7.csv',index_col='mean_depth')

def get_hs7(mean_depth):
    
    mean_depth_2dp = np.round(mean_depth+1e-6,2)
    
    hs7 = np.array(df.loc[mean_depth_2dp])
    
    return hs7
    
# Here's how to get seven snow depths of equal probability
# from one mean depth value

get_hs7(0.1285)

array([0.0559024 , 0.08756015, 0.10740861, 0.12619891, 0.1469113 ,
       0.17354443, 0.22748362])